name: Lua Testing

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
      - '**.log'
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        luaVersion: ['5.2', '5.3', '5.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: Setup LuaRocks
      run: |
        wget https://github.com/luarocks/luarocks/archive/v3.7.0.tar.gz -O /tmp/luarocks.tar.gz
        tar zxpf /tmp/luarocks.tar.gz -C ${{ github.workspace }}
        cd ${{ github.workspace }}/luarocks-3.7.0
        ./configure --with-lua=/usr/local
        make build
        sudo make install

#     - name: Cache Lua dependencies
#       uses: actions/cache@v2.1.6
#       with:
#         path: ~/.cache/luarocks
#         key: ${{ runner.os }}-luarocks-${{ hashFiles('**/rockspecs/*.rockspec') }}

#     - name: Install Lua dependencies
#       run: |
#         luarocks install --only-deps rockspecs/<mylibrary>.rockspec

#     - name: Build
#       run: |
#         luarocks make rockspecs/<mylibrary>.rockspec

    - name: Test
      run: |
        cd tests
        lua test_pprint.lua
        
    - name: Benchmakr
      run: |
        cd ../bench
        lua benchmark.lua
        
